version: '3.1'

services:
  
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile 
      
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports: 
      - "3000:3000"
    
    volumes:
      - ".:/app"
    